# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['script.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('media\\vega_toolbox.ico', 'media'),
        ('media\\teams.png', 'media'),
        ('media\\outlook.png', 'media'),
        ('media\\logo_vega.png', 'media'),
        ('media\\kiwi.png', 'media'),
        ('media\\Logo_Zucchetti.png', 'media'),
        ('media\\Logo_Zucchetti.png-small.png', 'media'),
        ('media\\icons\\parcourir.png', 'media\\icons'),
        ('media\\icons\\verifier.png', 'media\\icons'),
        ('media\\icons\\lancer.png', 'media\\icons'),
        ('media\\icons\\actualiser.png', 'media\\icons'),
        ('media\\icons\\retour.png', 'media\\icons'),
        ('media\\icons\\reparer.png', 'media\\icons'),
        ('media\\icons\\impression.png', 'media\\icons'),
        ('media\\icons\\journal.png', 'media\\icons'),
        ('media\\icons\\info.png', 'media\\icons'),
        ('media\\icons\\notepad.png', 'media\\icons'),
        ('media\\icons\\house.png', 'media\\icons'),
        ('media\\icons\\arrow_switch.png', 'media\\icons'),
        ('media\\icons\\shield.png', 'media\\icons'),
        ('media\\icons\\computer.png', 'media\\icons'),
        ('media\\icons\\bin.png', 'media\\icons'),
        ('media\\icons\\email_go.png', 'media\\icons'),
        ('media\\icons\\arrow_down.png', 'media\\icons'),
        ('media\\icons\\money_euro.png', 'media\\icons'),
        ('media\\icons\\hfsql.png', 'media\\icons'),
        ('media\\icons\\database.png', 'media\\icons'),
        ('media\\icons\\LICENSE_FAMFAMFAM_SILK.md', 'media\\icons'),
        ('lib\\CryptoTools.dll', 'lib'),
        ('lib\\Newtonsoft.Json.dll', 'lib'),
    ],
    hiddenimports=['msal', 'msal.application', 'msal.token_cache', 'truststore', 'tkinter', 'tkinter.ttk', 'tkinter.filedialog', 'tkinter.messagebox', 'httpx', 'httpcore', 'h2', 'hpack', 'hyperframe', 'h11', 'anyio', 'sniffio', 'idna', 'certifi', 'yaml'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='vega_toolbox',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    icon='media\\vega_toolbox.ico',
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
    version='version_info.txt',
)
